### ISSUE TITLE
Switch to GitLab or NotABug

### ISSUE THREAD

**Issue by gnunicode** [xianbaum/red-x#2]
It isn't possible to create an issue on GitHub without executing proprietary JavaScript, and, as the purpose of red-x is to reduce proprietary JavaScript, it would be great if this could be moved to either GitLab or NotABug, which both work without nonfree JS.

**Comment by xianbaum** [comment]
Are you sure? It seems to me that  GitHub is actually pretty functional with JavaScript disabled. I opened and closed this issue https://github.com/xianbaum/red-x/issues/3 without needing to enable JS and I am posting this comment without needing JS. I routinely do a lot on this site and never see the need to enable JS... HOWEVER since GitLab has a better track record with the FSF, I suppose I can move it there.

**Comment by xianbaum** [comment]
I will move this to GitLab later tonight.

**Comment by gnunicode** [comment]
Thanks. Yeah you're right - creating an issue does work if JS is completely disabled, but not with LibreJS installed - however some other functions don't work at all. GitLab also doesn't work with LibreJS but I know that all of the JS on GitLab is free whereas it isn't on GitHub. NotABug is LibreJS compatible but more obscure.

**Comment by xianbaum** [comment]
Sorry about the wait, I was pretty busy the past few days. https://gitlab.com/xianbaum/red-x/issues/2 I will point this repository to the GitLab one in in the readme
